[package]
name = "swing_library"
version = "0.1.0"
edition = "2021"

[dependencies]
rjvm_core = { git = "https://github.com/Lord-McSweeney/rjvm", rev = "dd53832c3579b7da17f8f252c017108d751e0ca0" }

[build-dependencies]
glob = "0.3.1"
