[package]
name = "swing_library"
version = "0.1.0"
edition = "2021"

[dependencies]
rjvm_core = { git = "https://github.com/Lord-McSweeney/rjvm", rev = "99d42e7f3e03d7de166203871582dceae466cee9" }
wasm-bindgen = "0.2.100"

[dependencies.web-sys]
features = ['Document', 'Element', 'HtmlElement', 'HtmlTextAreaElement', 'Node', 'Window']
version = "0.3.77"

[build-dependencies]
glob = "0.3.1"
